version: '3.8'

services:
  go:
    container_name: chi_go_backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./api/.env
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /go/src

  db:
    container_name: chi_mysql_db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - LC_ALL="C.utf8"
      - MYSQL_DATABASE=test_database
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - type: volume
        source: chi_mysql_db_volume
        target: /var/lib/mysql
      - type: bind
        source: ./mysql/my.cnf
        target: /etc/mysql/conf.d/my.cnf
      - type: bind
        source: ./mysql/schema/users.sql
        target: /docker-entrypoint-initdb.d/init.sql

volumes:
  chi_mysql_db_volume:
