name: Test & Build

on: [pull_request, push]

jobs:
  # 共通処理の実施
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Get Dependencies
        run: cd ./api \
             go mod tidy

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

  # ユニットテストの実施
  test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Test
        run: cd ./api \
             go test -v ./...

  # ビルドの実施
  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: cd ./api \
             go build ./...
