name: UnitTest

on:
  push:
    branches: main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Get Dependencies
        run: go mod tidy

      - name: Run Test
        run: go test -v ./...
